//
//  LocalizedStrings.swift
//  Bloom
//
//  Centralized localized string constants.
//  Replace all hard-coded Chinese strings in Views with L.xxx.
//  This file drives both the UI and the Localizable.strings lookup.
//
//  Usage:
//    Text(L.health)
//    Text(String(format: L.plantHasntWatered, arguments: [plantName]))
//

import Foundation

// MARK: - Helper
// A simple wrapper that returns NSLocalizedString(key, comment: key).
// Keeping the API short (L.xxx) to keep views readable.
enum L {
    private static func s(_ key: String) -> String {
        NSLocalizedString(key, comment: key)
    }
}

// MARK: - Garden (Extended)
extension L {
    // Alert buttons
    static let cancel              = s("取消")
    static let pause               = s("暂停")
    static let restore             = s("恢复")
    static let delete              = s("删除")
    static let undo                = s("撤销")
    static let gotIt               = s("我知道了")
    static let done                = s("完成")
    
    static let bloomTagline        = s("喝水养植物，一起变健康")
    
    // Harvest
    static let harvestFormat       = s("收获 %@")
    static let waterMoreForStage   = s("再浇点水就能到「%@」")
    static let pointsToNextStage   = s("距离下一阶段还差约 %d 点成长值")
    static let plantGrowingHealthily = s("植物正在健康成长中")
    static let readyToHarvest      = s("点击收获你的植物")
    static let harvestNowBadge     = s("可收获!")
    
    // Wilt celebration
    static let plantWilted         = s("植物枯萎了")
    static let startFromSeed       = s("没关系，从种子重新开始吧")
    static let dailyHydrationTip   = s("坚持每天喝水，植物就不会再枯萎啦")
    
    // Goal celebration
    static let goalAchieved        = s("🎉 今日目标达成！")
    static let keepUpGoodHabits    = s("你太棒了！\n继续加油，保持好习惯！")
    
    // Delete record
    static let deleteRecordConfirm = s("删除这条记录？")
    static let deleteRecordWarning = s("删除后将同步更新植物状态")
    static let deletedFormat       = s("已删除 %@")
    
    // Plant status
    static let plantHasntWatered   = s("%@ 还没喝到水")
    static let health              = s("健康度")
}

// MARK: - Statistics
extension L {
    static let waterTrend             = s("喝水趋势")
    static let peakHydrationTime      = s("最佳喝水时间")
    static let weeklyHabits           = s("每周习惯")
    static let achievementProgress    = s("成就进度")
    static let unlocked               = s("已解锁")
    static let advancedStats          = s("高级统计")
    static let deepInsights           = s("深度洞察")
    static let plantGrowthJourney     = s("植物成长历程")
    static let deepDataInsights      = s("深度数据洞察")
    static let deepInsightsExplain   = s("解锁达标率分析、平均完成度、成长历程等深度数据，更科学地养成喝水习惯。")
    // 时间周期（Statistics）
    static let periodWeek            = s("周")
    static let periodMonth          = s("月")
    static let periodQuarter        = s("季")
    static let periodYear           = s("年")
    // 收获
    static let plantMatured         = s("%@ 已成熟！")
    static let congratulations       = s("恭喜！")
    static let reachedStageMsg       = s("你的植物已经成长到 %@ 阶段")
    static let stage               = s("阶段")
    static let daysCared            = s("养护天数")
    static let daysN               = s("%d 天")
    static let harvestAndSave       = s("收获并保存到收藏")
    static let harvestPlantTitle    = s("收获植物")
    static let growthData           = s("成长数据")
    static let totalWaterAmount     = s("总浇水量")
    static let peakHealth           = s("最高健康度")
    static let shareHarvest         = s("分享收获")
    static let addedToCollectionHint = s("收获后将自动加入图鉴收藏")
    // 成长进度
    static let maxLevel             = s("已满级")
    static let growthProgress       = s("成长进度")
}

// MARK: - Achievements
extension L {
    static let achievements           = s("成就")
    static let achievementUnlocked    = s("成就解锁！")
    static let amazing                = s("太棒了！")
    // Format
    static let streakDaysAchieved     = s("连续 %d 天达标")
    static let keepGoingForStreak     = s("再坚持 %d 天 → %@ %@")
    static let nextStage              = s("下一阶段：%@")
    // Milestones
    static let milestone3    = s("初露锋芒")
    static let milestone7    = s("坚持一周")
    static let milestone14   = s("两周达人")
    static let milestone21   = s("三周传奇")
    static let milestone30   = s("满月之约")
    static let milestone60   = s("双月坚守")
    static let milestone100  = s("百日不辍")
}

// MARK: - Settings
extension L {
    static let settings               = s("设置")
    static let dailyGoal              = s("每日目标")
    static let recommended2000        = s("建议成人每日饮水 2000ml")
    static let everyXMinutes          = s("每 %d 分钟")
    static let reminders              = s("提醒")
    static let reminderExplain        = s("开启后，植物口渴时会提醒你来浇水")
    static let connectHealth          = s("连接健康 App")
    static let healthApp              = s("健康 App")
    static let healthConnected        = s("已连接健康 App")
    static let healthNotDetermined    = s("未决定")
    static let healthAuthorized       = s("已授权")
    static let healthDenied           = s("已拒绝")
    static let healthUnavailable      = s("不支持")
    static let writeToHealth          = s("写入健康 App")
    static let readFromHealth         = s("从健康 App 读取")
    static let syncFrequency          = s("同步频率")
    static let syncRealtime           = s("实时")
    static let syncHourly             = s("每小时")
    static let syncManual             = s("仅手动")
    static let healthLastSync         = s("上次同步")
    static let syncedDataCount        = s("已同步数据量")
    static let writtenCountFormat     = s("写入 %@ 条")
    static let readCountFormat        = s("读取 %@ 条")
    static let syncNow                = s("立即同步")
    static let healthSyncCompletedFormat    = s("同步完成，新增 %d 条记录")
    static let healthSyncFailed             = s("同步失败")
    static let manageInSettings       = s("在系统设置中管理权限")
    static let dataUsageExplanation   = s("数据使用说明")
    static let deleteBloomHealthData  = s("删除 Bloom 写入的健康数据")
    static let clearHealthData        = s("清除健康数据")
    static let clearHealthDataConfirm = s("将删除所有由 Bloom 写入健康 App 的喝水记录（共 %@ 条）。此操作不可撤销。")
    static let deletedHealthDataFormat = s("已删除 %d 条健康数据")
    static let healthDataUsage        = s("Bloom 仅请求饮水量数据，用于：")
    static let syncToHealth           = s("将你的喝水记录同步到健康 App")
    static let readFromHealthApps     = s("从健康 App 读取其他 App 记录的喝水数据")
    static let learnMore              = s("了解更多")
    static let healthSyncFooterAuthorized = s("喝水记录自动同步，数据仅存储在本地和健康 App 中")
    static let healthSyncFooterUnauthorized = s("同步喝水记录到健康 App")
    static let connect                = s("连接")
    static let connectHealthTitle     = s("连接健康 App")
    static let healthPermissionExplanation = s("Bloom 需要访问你的健康数据，以提供完整的植物养成体验。")
    static let writeData              = s("写入数据")
    static let writeDataDescription   = s("将你在 Bloom 中记录的喝水数据同步到健康 App")
    static let readData               = s("读取数据")
    static let readDataDescription    = s("从健康 App 读取其他 App 记录的喝水数据")
    static let privacyPromise         = s("隐私承诺")
    static let onlyRequestWaterData   = s("仅请求饮水量数据，不读取其他健康信息")
    static let dataStoredLocally      = s("数据仅保存在本地和健康 App 中")
    static let noThirdPartyUpload     = s("不会上传到任何第三方服务器")
    static let canDisableAnytime      = s("可随时在设置中关闭或删除数据")
    static let choosePermissionMode   = s("选择权限模式")
    static let readWriteRecommended   = s("读写（推荐）")
    static let writeOnly              = s("仅写入")
    static let readOnly               = s("仅读取")
    static let fullTwoWaySync         = s("完整的双向同步体验")
    static let onlySyncBloomToHealth  = s("只将 Bloom 的记录同步到健康 App")
    static let onlyReadFromHealth     = s("只从健康 App 读取其他记录")
    static let `continue`             = s("继续")
    static let healthDataPrivacy      = s("健康数据隐私")
    static let dataSecurityPriority   = s("你的数据安全是我们的首要任务")
    static let whatDataWeCollect      = s("我们收集什么数据")
    static let onlyRequestDietaryWater = s("仅请求饮水量（dietaryWater）数据")
    static let noOtherHealthData      = s("不读取步数、心率、睡眠等其他健康数据")
    static let noPersonalInfo         = s("不读取你的个人身份信息")
    static let howDataIsUsed          = s("数据如何使用")
    static let forPlantGrowth         = s("用于植物养成游戏：你喝水，植物成长")
    static let generateStats          = s("生成喝水统计和趋势分析")
    static let syncAcrossDevices      = s("在各设备间同步你的喝水记录")
    static let notForAds              = s("不会用于广告或用户画像")
    static let howDataIsStored        = s("数据如何存储")
    static let storedLocally          = s("数据保存在设备本地")
    static let iCloudEncryption       = s("通过 iCloud 同步时使用端到端加密")
    static let managedByApple         = s("健康 App 数据由 Apple 安全管理")
    static let noOwnServers           = s("我们没有自己的服务器存储你的数据")
    static let yourControl            = s("你的控制权")
    static let enableDisableSync      = s("可随时开启或关闭健康 App 同步")
    static let separatePermissions    = s("可单独控制写入和读取权限")
    static let oneTapDelete           = s("可一键删除所有 Bloom 写入的健康数据")
    static let revokeInSettings       = s("可在系统设置中完全撤销授权")
    static let viewFullPrivacyPolicy  = s("查看完整隐私政策")
    static let healthNotAvailable     = s("当前设备不支持健康 App")
    static let healthNotAuthorized    = s("尚未授权访问健康数据")
    static let healthWriteDisabled    = s("写入健康 App 功能已关闭")
    static let healthReadDisabled     = s("从健康 App 读取功能已关闭")
    static let healthDataUnavailable  = s("健康数据不可用")
    static let healthSyncErrorFormat  = s("健康数据同步失败：%@")
    static let goToSettingsToAuthorize = s("请在系统设置中允许 Bloom 访问健康数据")
    static let enableInSettings       = s("可在设置中开启健康 App 同步")
    static let tryAgainOrContact      = s("请稍后重试或联系支持")
    static let daysRemaining          = s("剩余 %@ 天")
    static let themeColor             = s("主题颜色")
    static let appearance             = s("外观")
    static let themeAppearance        = s("主题外观")
    static let chooseTheme            = s("选择你喜欢的主题外观")
    static let iCloudSync             = s("iCloud 同步")
    static let notSignedIn            = s("未登录")
    static let iCloudSyncExplain      = s("自动同步到 iCloud，多设备数据保持一致")
    static let syncCompleted          = s("同步完成")
    static let syncFailed             = s("同步失败")
    static let syncing                = s("同步中...")
    static let downloading            = s("下载中")
    static let merging                = s("合并中")
    static let uploading              = s("上传中")
    static let retry                  = s("重试")
    static let lastSync               = s("上次同步")
    static let iCloudNotSignedIn      = s("未登录 iCloud 账号")
    static let waitingForNetwork      = s("等待网络连接")
    static let iCloudStorageFull      = s("iCloud 存储空间不足")
    static let iCloudNoPermission     = s("无 iCloud 同步权限")
    static let networkError           = s("网络连接异常")
    static let signInToICloud         = s("请在系统设置中登录 iCloud")
    static let autoSyncWhenOnline     = s("连接网络后将自动同步")
    static let freeICloudStorage      = s("请清理 iCloud 存储空间后重试")
    static let allowICloudAccess      = s("请在系统设置中允许 Bloom 访问 iCloud")
    static let checkNetworkAndRetry   = s("请检查网络连接后重试")
    static let tryAgainLater          = s("请稍后重试")
    static let signInToEnableSync     = s("请在系统设置中登录 iCloud 以启用同步")
    static let syncingPleaseWait      = s("正在同步数据，请稍候...")
    static let dataBackup             = s("数据备份")
    static let exportBackup           = s("导出数据备份")
    static let restoreFromBackup      = s("从备份恢复")
    static let lastBackup             = s("上次备份")
    static let exportExplain          = s("导出 JSON 文件可保存到 Files App，用于数据备份或迁移")
    static let bloomProUnlocked       = s("Bloom Pro 已解锁")
    static let upgradeBloomPro        = s("升级 Bloom Pro")
    static let unlockMoreSpecies      = s("解锁更多品种")
    static let version                = s("版本")
    static let about                  = s("关于")
    static let plantName              = s("植物名字")
    static let pauseCare              = s("暂停养护")
    static let carePaused             = s("养护已暂停")
    static let pauseExplanation       = s("暂停期间植物不会枯萎，最多14天")
    static let resumeCare             = s("恢复养护")
    static let businessTravel         = s("出差/旅行")
    static let goToSettings           = s("去设置")
    static let restorePurchases       = s("恢复购买")
    static let restoreSuccessful      = s("恢复成功")
    static let restoreFailed          = s("恢复失败")
    static let noPurchasesFound       = s("未找到已购买的记录")
    static let dataRestored           = s("数据已成功恢复")
    static let allowHealth            = s("请在系统设置中允许 Bloom 访问健康数据")
    static let allowNotifications     = s("请在系统设置中允许 Bloom 发送通知")
    static let healthPermission       = s("健康权限")
    static let notificationPermission = s("通知权限")
    static let confirmResumeCare      = s("确定要恢复养护吗？植物将重新开始生长。")
    static let proThankYou            = s("感谢您的支持！Pro 权益已解锁。")
    static let ok                    = s("好的")
    
    // 评分与分享
    static let rateUs                = s("给我们评分")
    static let rateUsOnAppStore      = s("在 App Store 给我们评分")
    static let shareWithFriends      = s("分享给朋友")
    static let shareBloom            = s("分享 Bloom")
    static let aboutUs               = s("关于我们")
    static let contactUs             = s("联系我们")
    static let feedback              = s("意见反馈")
    static let followUs              = s("关注我们")
    static let later                 = s("稍后再说")
    static let neverRemind           = s("不再提示")
    static let enjoyBloom            = s("喜欢 Bloom 吗？")
    static let rateUsPrompt          = s("给我们评分，帮助更多人发现 Bloom")
    static let thankYouForRating     = s("感谢您的评价！")
}

// MARK: - Paywall
extension L {
    static let unlockBloomPro         = s("解锁 Bloom Pro")
    static let waterLog               = s("喝水记录")
    static let unlockMoreLives        = s("解锁更多生命")
    static let buildBeautifulGarden   = s("养出更美的花园，收集全部品种")
    static let upgradeToPro           = s("升级 Pro")
    static let unlimitedSpecies       = s("无限植物品种")
    static let all7PlantsDreamGarden  = s("解锁全部7种植物，打造梦幻花园")
    static let autoRenewExplain       = s("订阅自动续期，可随时在系统设置中取消")
    static let bestValue              = s("最划算")
    static let close                  = s("关闭")
    static let loading               = s("正在加载...")
    // Paywall feature descriptions
    static let advancedStatistics      = s("高级统计")
    static let advancedStatisticsDesc = s("完整的数据分析和可视化报告")
    static let customThemes          = s("自定义主题")
    static let customThemesDesc      = s("解锁所有 Pro 主题和外观")
    static let proThemes            = s("Pro 主题")
    static let harvested            = s("已收获")
    static let total               = s("总计")
    static let myGarden            = s("我的花园")
    static let currentlyCaring      = s("正在养护")
    static let harvestWall          = s("收获墙")
    static let daysToHarvest        = s("%d 天养成")
    static let speciesCodex         = s("品种图鉴")
    static let mysterySpecies       = s("???")
    static let collected            = s("已收集")
    static let harvestCount         = s("收获 %d 次")
    static let proUnlock            = s("Pro 解锁")
    static let notCollected         = s("未收集")
    static let collectionProgress   = s("收集进度")
    static let collectionProgressHint = s("已收集 %d / 共 %d 种植物")
    static let allCollected         = s("全部收集!")
    static let totalHarvests        = s("总收获")
    static let speciesCollected     = s("已收集")
    static let totalSpecies         = s("全部品种")
    static let speciesInfo          = s("品种信息")
    static let scientificName       = s("学名")
    static let difficulty           = s("难度")
    static let waterNeed            = s("需水量")
    static let bloomColor           = s("开花颜色")
    static let growthDays           = s("生长周期")
    static let harvestHistory       = s("收获记录")
    static let noHarvestYet         = s("还没有收获过哦")
    static let unlimitedPlants       = s("无限植物")
    static let unlimitedPlantsDesc   = s("解锁全部 7 种植物，打造梦幻花园")
    static let multiDeviceSync       = s("多设备同步")
    static let multiDeviceSyncDesc   = s("CloudKit 数据同步和备份")
    static let lifetimePurchase      = s("终身购买")
    static let proYearly            = s("Pro 年订阅")
    static let oneTimePurchase      = s("一次性购买，永久解锁")
    static let unlimitedCareAllYear  = s("全年无限养护")
    static let savePercent          = s("省 %d%% 相比订阅")
    static let popular             = s("人气之选")
    static let termsOfService        = s("服务条款")
    static let privacyPolicy         = s("隐私政策")
}

// MARK: - Dev / IAP
extension L {
    static let sandboxMode            = s("⚠️ 沙盒测试模式")
    static let devMode                = s("🧪 开发模式")
    static let configureIAPFirst      = s("请在 App Store Connect 配置商品后测试")
    static let addEnvVar              = s("或在 Scheme 中添加 BLOOM_DEV_MODE=1 环境变量")
    static let noIAPConfigured        = s("暂未配置内购商品")
}

// MARK: - Onboarding
extension L {
    static let keepPlantAlive         = s("养活一株植物")
    static let justByDrinking         = s("只需要你好好喝水")
    static let growsWithEverySip      = s("你每喝一口水，它就长大一点")
    static let meetYourPlant          = s("认识一下你的植物")
    static let giveItAName            = s("给它起个名字")
    static let dailyWaterGoal         = s("每日喝水目标")
    static let mlPerDay2000           = s("ml / 天 · 建议成人每日 2000ml")
    static let letPlantTellYou        = s("让 %@ 在渴的时候")
    static let canTellYou             = s("能告诉你")
    static let notificationExplain    = s("开启通知，它口渴时会提醒你来浇水。\n不开启也可以，但你可能会忘了它。")
    static let notNow                 = s("暂不开启")
    static let defaultPlantName       = s("小绿")  // 默认植物名
}

// MARK: - 分享
extension L {
    static let sharePlantText         = s("我在用 Bloom 养植物「%@」，喝水也能变得有趣！%@")
    static let shareAchievementText   = s("我在 Bloom 解锁了新成就！喝水养植物，一起养成好习惯 🌱 %@")
    static let shareStreakText        = s("用 Bloom 养成喝水好习惯，我已经连续 %d 天达标了！🌿 %@")
    static let shareGardenText        = s("我在 Bloom 收集了好多植物品种，你的花园收集了多少？🌺 %@")
    static let shareAppText           = s("推荐一个超棒的喝水 App — Bloom！用植物养成的方式，让喝水变得有趣 🌱 %@")
    
    static let streakAchieved         = s("连续达标")
    static let daysConsecutive        = s("天")
    static let keepItUp               = s("继续保持，你真棒！")
    
    static let myGardenCollection     = s("我的花园收藏")
    static let sharedSpeciesCollected = s("种植物已收集")
    static let collectionProgressPercent = s("完成 %d%%")
}
